# https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
auto_detect_solc = true
libs = ["lib"]
out = 'out'
solc = "0.8.19"
src = 'src'

fs_permissions = [
  {access = "read-write", path = "./addresses.json"},
  {access = "read-write", path = "./out"},
]

[rpc_endpoints]
mainnet = "https://rpc.ankr.com/eth"
mainnet2 = "https://mainnet.infura.io/v3/${INFURA_API_KEY}"
mainnet3 = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

arbitrum = "https://arbitrum-mainnet.infura.io/v3/${INFURA_API_KEY}"
arbitrum2 = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

optimism = "https://rpc.ankr.com/optimism"
optimism2 = "https://optimism-mainnet.infura.io/v3/${INFURA_API_KEY}"
optimism3 = "https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY_OPTIMISM}"
optimism4 = "https://mainnet.optimism.io"

linea = "https://rpc.linea.build/"
linea2 = "https://linea-mainnet.infura.io/v3/${INFURA_API_KEY}"

base = "https://rpc.ankr.com/base"
base2 = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY_BASE}"

pgn = "https://rpc.publicgoods.network"
zora = "https://rpc.zora.energy"

polygon = "https://polygon-mainnet.infura.io/v3/${INFURA_API_KEY}"
polygon2 = "https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY_POLYGON}"
polygon3 = "https://polygon-rpc.com/"

polygon-zkevm = "https://zkevm-rpc.com"

gnosis = "https://rpc.ankr.com/gnosis"
gnosis2 = "https://rpc.gnosis.io"

avalanche = "https://rpc.ankr.com/avalanche"
avalanche2 = "https://avalanche-mainnet.infura.io/v3/${INFURA_API_KEY}"
avalanche3 = "https://api.avax.network/ext/bc/C/rpc"

fantom = "https://rpc.ankr.com/fantom"
fantom2 = "https://rpc.ftm.tools"
fantom3 = "https://rpcapi.fantom.network"

bsc = "https://rpc.ankr.com/bsc"
bsc2 = "https://bsc-dataseed.binance.org"

zksync = "https://mainnet.era.zksync.io"
fevm = "https://api.node.glif.io/rpc/v1"
nova = "https://nova.arbitrum.io/rpc"
scroll = "https://rpc.scroll.io"
zkevm = "https://zkevm-rpc.com"

mantle = "https://rpc.ankr.com/mantle"
mode = "https://mainnet.mode.network"

dymension = "https://dymension-evm.blockpi.network/v1/rpc/public"

# testnets

bsctestnet = "https://rpc.ankr.com/bsc_testnet_chapel"
bsctestnet2 = "https://data-seed-prebsc-1-s1.binance.org:8545"

sepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"
sepolia2 = "https://rpc.sepolia.com"

holesky = "https://ethereum-holesky.publicnode.com"

goerli = "https://goerli.infura.io/v3/${INFURA_API_KEY}"
goerli2 = "https://eth-goerli.g.alchemy.com/v2/${ALCHEMY_API_KEY_GOERLI}"

optimism-goerli = "https://optimism-goerli.publicnode.com"
optimism-sepolia = "https://optimism-sepolia.infura.io/v3/${INFURA_API_KEY}"

arbitrum-sepolia = "https://arbitrum-sepolia.infura.io/v3/${INFURA_API_KEY}"

mumbai = "https://rpc.ankr.com/polygon_mumbai"
mumbai2 = "https://polygon-mumbai.infura.io/v3/${INFURA_API_KEY}"
polygon-zkevm-testnet = "https://rpc.public.zkevm-test.net"

base-goerli = "https://goerli.base.org/"
base-goerli2 = "https://rpc.ankr.com/base_goerli"
base-sepolia = "https://sepolia.base.org/"

fuji = "https://avalanche-fuji.infura.io/v3/${INFURA_API_KEY}"

mode-testnet = "https://sepolia.mode.network"
pgn-sepolia = "https://sepolia.publicgoods.network"
zora-goerli = "https://testnet.rpc.zora.co"
zora-sepolia = "https://sepolia.rpc.zora.energy"

calib = "https://api.calibration.node.glif.io/rpc/v1"
linea-testnet = "https://rpc.goerli.linea.build/"

chiado = "https://rpc.chiadochain.net"
telos-testnet = "https://testnet.telos.net/evm"

zksync-sepolia = "https://sepolia.era.zksync.dev"
calibration = "${CALIBRATIONNET_RPC_URL}"
scroll-alpha-testnet = "https://alpha-rpc.scroll.io/l2"
scroll-sepolia = "https://sepolia-rpc.scroll.io/"

mantle-testnet = "https://rpc.testnet.mantle.xyz"
taiko-jolnir = "https://rpc.jolnir.taiko.xyz"
mode-sepolia = "https://sepolia.mode.network"

chaos = "https://staging-v3.skalenodes.com/v1/staging-fast-active-bellatrix"

anvil = "http://127.0.0.1:8545"
local = "http://127.0.0.1:8545"

[etherscan]
gnosis = {key = "${ETHERSCAN_API_KEY_GNOSIS}"}
mainnet = {key = "${ETHERSCAN_API_KEY_ETHEREUM}"}

base = {key = "${ETHERSCAN_API_KEY_BASE}"}
linea = {key = "${ETHERSCAN_API_KEY_LINEA}"}

arbitrum = {key = "${ETHERSCAN_API_KEY_ARBITRUM }"}
optimism = {key = "${ETHERSCAN_API_KEY_OPTIMISM}"}

scroll = {key = "${ETHERSCAN_API_KEY_SCROLL}", url = "https://api.scrollscan.com/api"}

polygon = {key = "${ETHERSCAN_API_KEY_POLYGON}"}
polygon-zkevm =  { key = "${ETHERSCAN_API_KEY_POLYGON_ZKEVM}" }

avalanche = {key = "${ETHERSCAN_API_KEY_AVALANCHE}"}
bsc = {key = "${ETHERSCAN_API_KEY_BINANCE}"}
fantom = {key = "${ETHERSCAN_API_KEY_FANTOM}"}

mantle = {key = "", url = "https://explorer.mantle.xyz/api"}

# testnets
goerli = {key = "${ETHERSCAN_API_KEY_ETHEREUM}"}
sepolia = {key = "${ETHERSCAN_API_KEY_ETHEREUM}"}
holesky = {key = "${ETHERSCAN_API_KEY}", url = "https://api-holesky.etherscan.io/api"}

base-goerli = {key = "${ETHERSCAN_API_KEY_BASE}"}
linea-testnet = {key = "${ETHERSCAN_API_KEY_LINEA}", url = "https://api.lineascan.build/api"}
base-sepolia = { key = "${ETHERSCAN_API_KEY_BASE}" }

chiado = {key = "${ETHERSCAN_API_KEY_GNOSIS}"}
optimism-goerli = {key = "${ETHERSCAN_API_KEY_OPTIMISM}"}
polygon-zkevm-testnet =  { key = "${ETHERSCAN_API_KEY_POLYGON_ZKEVM}" }

mantle-testnet = {key = "", url = "https://explorer.testnet/mantle.xyz/api"}
