# https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
auto_detect_solc = true
libs = ["lib"]
out = 'out'
solc = "0.8.19"
src = 'src'

fs_permissions = [
  {access = "read-write", path = "./addresses.json"},
  {access = "read-write", path = "./out"},
]

[rpc_endpoints]
mainnet = "https://rpc.ankr.com/eth"
mainnet2 = "https://mainnet.infura.io/v3/${INFURA_API_KEY}"
mainnet3 = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

arbitrum = "https://arbitrum-mainnet.infura.io/v3/${INFURA_API_KEY}"
arbitrum2 = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

optimism = "https://rpc.ankr.com/optimism"
optimism2 = "https://optimism-mainnet.infura.io/v3/${INFURA_API_KEY}"
optimism3 = "https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY_OPTIMISM}"
optimism4 = "https://mainnet.optimism.io"

linea = "https://rpc.linea.build/"

base = "https://rpc.ankr.com/base"
pgn = "https://rpc.publicgoods.network"
zora = "https://rpc.zora.energy"

polygon = "https://polygon-mainnet.infura.io/v3/${INFURA_API_KEY}"
polygon2 = "https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY_POLYGON}"
polygon3 = "https://polygon-rpc.com/"

polygon-zkevm = "https://zkevm-rpc.com"

gnosis = "https://rpc.ankr.com/gnosis"
gnosis2 = "https://rpc.gnosis.io"

avalanche = "https://rpc.ankr.com/avalanche"
avalanche2 = "https://avalanche-mainnet.infura.io/v3/${INFURA_API_KEY}"
avalanche3 = "https://api.avax.network/ext/bc/C/rpc"

fantom = "https://rpc.ankr.com/fantom"
fantom2 = "https://rpc.ftm.tools"
fantom3 = "https://rpcapi.fantom.network"

bsc = "https://rpc.ankr.com/bsc"
bsc2 = "https://bsc-dataseed.binance.org"

era = "https://mainnet.era.zksync.io"
fevm = "https://api.node.glif.io/rpc/v1"
nova = "https://nova.arbitrum.io/rpc"
scroll = "https://rpc.scroll.io"
zkevm = "https://zkevm-rpc.com"

# testnets
bsctestnet = "https://rpc.ankr.com/bsc_testnet_chapel"
bsctestnet2 = "https://data-seed-prebsc-1-s1.binance.org:8545"

sepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"
sepolia2 = "https://rpc.sepolia.com"

holesky = "https://ethereum-holesky.publicnode.com"

goerli = "https://goerli.infura.io/v3/${INFURA_API_KEY}"
goerli2 = "https://eth-goerli.g.alchemy.com/v2/${ALCHEMY_API_KEY_GOERLI}"

optimism-goerli = "https://optimism-goerli.publicnode.com"

mumbai = "https://rpc.ankr.com/polygon_mumbai"
mumbai2 = "https://polygon-mumbai.infura.io/v3/${INFURA_API_KEY}"
polygon-zkevm-testnet = "https://rpc.public.zkevm-test.net"

base-goerli = "https://goerli.base.org/"
base-goerli2 = "https://rpc.ankr.com/base_goerli"
mode-testnet = "https://sepolia.mode.network"
pgn-sepolia = "https://sepolia.publicgoods.network"
zora-testnet = "https://testnet.rpc.zora.co"

calib = "https://api.calibration.node.glif.io/rpc/v1"
 = "https://rpc.goerli.linea.build/"
taiko = "https://rpc.a2.taiko.xyz"

chiado = "https://rpc.chiadochain.net"
local = "http://127.0.0.1:8545"
telostestnet = "https://testnet.telos.net/evm"

calibration = "${CALIBRATIONNET_RPC_URL}"
scroll-alpha-testnet = "https://alpha-rpc.scroll.io/l2"
scroll-sepolia = "https://sepolia-rpc.scroll.io/"

[etherscan]
gnosis = {key = "${ETHERSCAN_API_KEY_GNOSIS}"}
mainnet = {key = "${ETHERSCAN_API_KEY_ETHEREUM}"}

base = {key = "${ETHERSCAN_API_KEY_BASE}"}
linea = {key = "${ETHERSCAN_API_KEY_LINEA}"}

arbitrum = {key = "${ETHERSCAN_API_KEY_ARBITRUM }"}
optimism = {key = "${ETHERSCAN_API_KEY_OPTIMISM}"}

polygon = {key = "${ETHERSCAN_API_KEY_POLYGON}"}

avalanche = {key = "${ETHERSCAN_API_KEY_AVALANCHE}"}
bsc = {key = "${ETHERSCAN_API_KEY_BINANCE}"}
fantom = {key = "${ETHERSCAN_API_KEY_FANTOM}"}

# testnets
goerli = {key = "${ETHERSCAN_API_KEY_ETHEREUM}"}
sepolia = {key = "${ETHERSCAN_API_KEY_ETHEREUM}"}
# holesky = {key = "${ETHERSCAN_API_KEY_ETHEREUM}"}
holesky = { key = "${ETHERSCAN_API_KEY}", url = "https://api-holesky.etherscan.io/api" }

base-goerli = {key = "${ETHERSCAN_API_KEY_BASE}"}
chiado = {key = "${ETHERSCAN_API_KEY_GNOSIS}"}
optimism-goerli = {key = "${ETHERSCAN_API_KEY_OPTIMISM}"}
