# https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
src = 'src'
out = 'out'
libs = ["lib"]
auto_detect_solc = true
# solc = "0.8.18"

[rpc_endpoints]
mainnet = "https://rpc.ankr.com/eth"
mainnet1 = "https://mainnet.infura.io/v3/${INFURA_API_KEY}"
mainnet2 = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

arbitrum = "https://arbitrum-mainnet.infura.io/v3/${INFURA_API_KEY}"
arbitrum1 = "https://arbitrum-mainnet.infura.io/v3/${INFURA_API_KEY}"
arbitrum2 = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

optimism = "https://rpc.ankr.com/optimism"
optimism1 = "https://optimism-mainnet.infura.io/v3/${INFURA_API_KEY}"
optimism2 = "https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY_OPTIMISM}"
optimism3 = "https://mainnet.optimism.io"

polygon = "https://polygon-mainnet.infura.io/v3/${INFURA_API_KEY}"
polygon1 = "https://polygon-mainnet.infura.io/v3/${INFURA_API_KEY}"
polygon2 = "https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY_POLYGON}"
polygon3 = "https://polygon-rpc.com/"

gnosis = "https://rpc.ankr.com/gnosis"
gnosis1 = "https://rpc.gnosis.io"

avalanche = "https://rpc.ankr.com/avalanche"
avalanche1 = "https://avalanche-mainnet.infura.io/v3/${INFURA_API_KEY}"
avalanche3 = "https://api.avax.network/ext/bc/C/rpc"

fantom = "https://rpc.ankr.com/fantom"
fantom3 = "https://rpcapi.fantom.network"
fantom4 = "https://rpc.ftm.tools"

bsc = "https://rpc.ankr.com/bsc"
bsc3 = "https://bsc-dataseed.binance.org"

nova = "https://nova.arbitrum.io/rpc"
zkevm = "https://zkevm-rpc.com"
era = "https://mainnet.era.zksync.io"
fevm = "https://api.node.glif.io/rpc/v1"

# TESTNETS
bsctestnet = "https://rpc.ankr.com/bsc_testnet_chapel"
bsctestnet3 = "https://data-seed-prebsc-1-s1.binance.org:8545"

sepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"
sepolia1 = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"
sepolia3 = "https://rpc.sepolia.com"

goerli = "https://goerli.infura.io/v3/${INFURA_API_KEY}"
goerli1 = "https://goerli.infura.io/v3/${INFURA_API_KEY}"
goerli2 = "https://eth-goerli.g.alchemy.com/v2/${ALCHEMY_API_KEY_GOERLI}"

mumbai = "https://rpc.ankr.com/polygon_mumbai"
mumbai1 = "https://polygon-mumbai.infura.io/v3/${INFURA_API_KEY}"

scroll = "https://alpha-rpc.scroll.io/l2"
base = "https://goerli.base.org/"
taiko = "https://rpc.a2.taiko.xyz"
linea = "https://rpc.goerli.linea.build/"
calib = "https://api.calibration.node.glif.io/rpc/v1"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

arbitrum = { key = "${ETHERSCAN_API_KEY_ARBITRUM }" }
optimism = { key = "${ETHERSCAN_API_KEY_OPTIMISM}" }

polygon = { key = "${ETHERSCAN_API_KEY_POLYGON}" }
bsc = { key = "${ETHERSCAN_API_KEY_BINANCE}" }
fantom = { key = "${ETHERSCAN_API_KEY_FANTOM}" }
avalanche = { key = "${ETHERSCAN_API_KEY_AVALANCHE}" }
